DBPATH: db\players\players.db
INPUT_DIFFICULTY_PROMPT : |
  'e': easy
  'm': medium,
  'd': difficult
  Your choice:
MAIN_PROMPT: |
  What do you want to do: 
  'l' : login
  's' : signup
  'q' : quit
  Your Choice:
ADMIN_PROMPT: |
  Press:
  'l': leaderboard section
  'w' : word list section
  's' : Your stats
  'p' : New Game
  'q' : logout
  Your Choice:
PLAYER_PROMPT: |
  Press:
  'p': For a new game
  's': Your stats
  'l': leaderboard
  'q': logout
  Your choice:
MODIFY_GAME_PROMPT: |
  What do you want to modify?
  'r': number of rounds
  'd': difficulty levels
  'b': back
SECURE_PASSWORD_PROMPT: |
  Your password must contain:
  1. Minimum eight characters, 
  2. at least one uppercase letter,
  3. one lowercase letter and one number
  New Password:
WORD_SECTION_PROMPT : |
  'a': Add new word
  'p': print all words available
  'u': update a particular word
  'd': delete a particular word
  'q': back to admin panel
  Your choice: