CREATE_TABLE_QUERY : CREATE TABLE IF NOT EXISTS game_config(config_id INTEGER PRIMARY KEY AUTOINCREMENT, config_name TEXT, config_key TEXT, config_value INTEGER)
GAME_CONFIG_QUERY : SELECT * FROM game_config WHERE config_name=?
CREATE_TABLE_AUTH : CREATE TABLE IF NOT EXISTS auth_table(user_id PRIMARY KEY,uname TEXT, password TEXT, role TEXT)
CREATE_TABLE_PLAYER : CREATE TABLE IF NOT EXISTS players(user_id TEXT PRIMARY KEY, high_score REAL, total_game INTEGER, total_games_won INTEGER, high_score_created_on timestamp, FOREIGN KEY (user_id) REFERENCES auth_table(user_id))
FIND_USER_QUERY : SELECT * FROM auth_table WHERE user_id=?
INSERT_INTO_AUTH : INSERT INTO auth_table VALUES(?,?,?, ?)
INSERT_INTO_PLAYERS : INSERT INTO players VALUES(?,0,0,0,?)
PLAYER_DATA : SELECT * FROM players WHERE user_id=?
UPDATE_HIGH_SCORE : UPDATE players SET high_score = ?, high_score_created_on=?  WHERE user_id = ?
GET_LEADERBOARD : SELECT uname, high_score,high_score_created_on from players ORDER BY high_score DESC,high_score_created_on DESC LIMIT 10
UPDATE_PLAYER_STATS : UPDATE players SET total_game = ?, total_games_won=? WHERE user_id = ?
USER_WITH_UNAME : SELECT * FROM auth_table WHERE uname=?
