WELCOME_TO_WORD_SECTION : Welcome to word section
OUT_OF_WORDS : No words found!
INPUT_WORD_MAIN_PROMPT : "Please enter the following details to add a new word"
INPUT_NEW_WORD_PROMPT : "New Word: "
INPUT_NEW_WORD_DEFINITION : "Enter a hint or definition for the new word: "
EMPTY_NEW_WORD : "New Word can't be empty: "
EMPTY_NEW_WORD_DEFINITION : "A hint must be given for the new word: "
INPUT_NEW_WORD_SOURCE : "A source or url for the new word: "
EMPTY_NEW_WORD_SOURCE : "Source of the new word can't be empty: "
WORDS_FILE_PATH : .\src\word_section\words.txt
DELETE_PROMPT : "Enter the word you want to delete: "
UPDATE_WORD : "Enter the word you want to update: "
UPDATE_NEW_DEFINITION : "Enter the new definition: "
UPDATE_WORD_EMPTY : Word to update can't be empty
UPDATE_DEFINITION_EMPTY : New definition cant be empty
SUCCESS_UPDATE : "Successfully changed the definition of {} to {}"
SUCCESS_DELETE : "Successfully deleted the word {}"
SUCCESS_ADD : "Successfully added the word {}"
PRINT_FORMATTED_WORD : "{} - {}"
ALL_WORDS_PROMPT : Here are the available words
END_OF_WORDS : That's all the words we have
ALL_WORDS_MENU_PROMPT : |
  'u': update a word
  'd': delete a word
  'n': next page
  'q': back
  Your choice:
INVALID_INPUT : "Invalid input try again: "
UPDATE_WORD_MAIN_PROMPT : "Please enter the following details to update a word"